spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/parcialdb}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET:clave-desarrollo-no-usar-en-produccion-debe-ser-larga-minimo-64-caracteres-aqui}
jwt.expiration=${JWT_EXPIRATION:86400000}

server.port=${SERVER_PORT:8080}

springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true